// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./resources/src/App.vue')['default']
    Calendar: typeof import('./resources/src/components/Calendar.vue')['default']
    Footer: typeof import('./resources/src/components/Footer.vue')['default']
    Header: typeof import('./resources/src/components/Header.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VFooter: typeof import('vuetify/components')['VFooter']
    VMain: typeof import('vuetify/components')['VMain']
  }
}
